config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :questions, controller: 'topics', except: [:destroy] do
    resources :answers, controller: 'messages',
              only: [:create, :edit, :update] do
      post :accept, on: :member
      post :voteup, on: :member
      post :votedown, on: :member
    end
    post :subscribe, on: :member
    post :unsubscribe, on: :member
  end

  resources :messages, only: [] do
    resources :comments, only: [:create]
  end

  resources :users, only: [:show, :edit, :update]

  resources :tags, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, controller: 'topics',
                only: [:index, :show, :create] do
        resources :answers, controller: 'messages',
                  only: [:index, :show, :create]
      end
    end
  end

  root 'topics#home'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, presence: true
  validates :views, numericality: true

  has_many :messages
  has_one :question, -> { where(answer: false) }, class_name: 'Message'
  has_many :answers, -> { where(answer: true).order(accepted: :desc, score: :desc, updated_at: :desc) },
           class_name: 'Message'

  has_many :topic_tags
  has_many :tags, through: :topic_tags

  has_many :subscriptions

  accepts_nested_attributes_for :question

  delegate :author, :author=, to: :question

  def self.for_home_page
    includes(:tags, question: :author).order(created_at: :desc).limit(20)
  end

  def self.with_questions_by(user)
    joins(:question).where(messages: { author_id: user })
      .order(updated_at: :desc).limit(10)
  end

  def self.with_answers_by(user)
    connection.select_all %Q(
      select t.id as topic_id, t.title, m.id as message_id
      from messages m, topics t
      where t.id = m.topic_id
        and m.answer = 't'
        and m.author_id = #{user.id}
      order by m.updated_at desc
      limit 10)
  end

  def self.daily_digest_for(range)
    order(:created_at).where(created_at: range)
  end

  def answers_count
    messages_count - 1
  end

  def has_answers?
    answers_count > 0
  end

  def has_accepted_answer?
    answers.select { |a| a.accepted }.size > 0
  end

  def answered_by?(user)
    if has_answers?
      answers.map { |answer| answer.author }.include? user
    else
      false
    end
  end

  def answer_id_by(user)
    answers.where(author: user).first.id
  end

  def increment_views
    self.views += 1
    self.save!
  end

  after_initialize :set_defaults

  private

  def set_defaults
    self.views ||= 0
  end
end

app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < Api::V1::BaseController
  respond_to :json, only: [:index, :show, :create]
  actions :index, :show, :create
  defaults resource_class: Topic

  def index
    respond_with TopicsSerializer.to_hash(collection)
  end

  def show
    respond_with TopicsSerializer.new(resource).to_hash type: :api_resource
  end

  def create
    build_resource.question.author = current_resource_owner
    create! do |success, failure|
      success.json do
        TagService.process params[:topic][:tags], for: resource
        render json: TopicsSerializer.new(resource).to_hash(type: :api_resource)
      end
    end
  end

  private

  def topic_params
    params.require(:topic).permit(:title, question_attributes: [:id, :body])
  end
end

app/controllers/topics_controller.rb
class TopicsController < InheritedResources::Base
  before_action :authenticate_user!, except: [:home, :index, :show]
  actions :all, except: :destroy
  custom_actions resource: [:subscribe, :unsubscribe]
  respond_to :js, only: [:subscribe, :unsubscribe]

  load_and_authorize_resource
  skip_load_resource only: [:home, :index, :show]
  skip_authorize_resource only: [:home, :index, :show]

  def home
    @topics = Topic.for_home_page.decorate
  end

  def index
    if params[:search]
      @topics = Topic.search(params[:search]).map { |t| t.decorate }
    else
      @topics = Topic.includes(:tags, question: :author).all.decorate
    end
  end

  def show
    include_params = { answers: [:author, :attachments, { comments: :author }] }
    @topic = Topic.includes(:question, include_params).find(params[:id]).decorate
    @topic.increment_views
    @answer = @topic.answers.build
  end

  def new
    build_resource.build_question
  end

  def create
    resource.question.author = current_user
    create! do |success, failure|
      success.html do
        TagService.process params[:topic][:tags], for: resource
        subscribe
        publish_new_topic
        redirect_to question_path(resource)
      end
    end
  end

  def update
    update! do |success, failure|
      success.html do
        TagService.process params[:topic][:tags], for: resource
        redirect_to question_path(resource)
      end
    end
  end

  def subscribe
    Subscription.create!(topic: resource, user: current_user)
  end

  def unsubscribe
    Subscription.where(topic: resource, user: current_user).destroy_all
  end

  private

  def publish_new_topic
    data = TopicsSerializer.new(resource).to_hash type: :private_pub
    PrivatePub.publish_to '/topics/new', data
  end

  def topic_params
    params.require(:topic).permit(
      :title,
      question_attributes: [:id, :body,
                            attachments_attributes: [:file]]
    )
  end
end

app/helpers/topic_helper.rb
module TopicHelper
  def answer_path(answer)
    "#{question_path(answer['topic_id'])}/#message-#{answer['message_id']}"
  end

  def markdown(source)
    @renderer ||= Redcarpet::Render::HTML.new(escape_html: true)
    @markdown ||= Redcarpet::Markdown.new(@renderer, autolink: true)
    @markdown.render(source).html_safe
  end
end

app/views/topics/_answered.html.slim
p
  ' You already
  a> href="#{topic.message_id_by current_user}" class='answer-link'
    | answered
  | this question

app/views/topics/_answers.html.slim
h3 = pluralize answers_count, 'Answer'
ul
  - answers.each do |answer|
    - if answer.persisted?
      hr
      li = render answer

app/views/topics/_comments.html.slim
- comments.each do |comment|
  - if comment.persisted?
    li.comment
      => comment.body
      ' &mdash;
      => link_to comment.author.name, user_path(comment.author)
      = timeago_tag comment.created_at

app/views/topics/_topic.html.slim
li
  .row
    .col-md-4.col-lg-3.counters
      .votes
        .mini-counts = topic.question.score
        p.small = topic.votes_label
      .answers class=topic.answers_class
        .mini-counts = topic.answers_count
        p.small = topic.answers_label
      .views
        .mini-counts = topic.views
        p.small = topic.views_label
    .col-md-8.col-lg-9.summary
      h3 = link_to topic.title, question_path(topic)
      .last-activity
        => link_to topic.author.name, topic.author
        span title='reputation score'
          = topic.author.reputation
      p.tags = topic.tags_list
  hr

app/views/topics/edit.html.slim
= bootstrap_nested_form_for @topic, url: question_path(@topic) do |f|
  = f.text_field :title, autofocus: true
  = f.fields_for :question do |q|
    = q.text_area :body, hide_label: :true, rows: 10
    = f.text_field :tags, value: @topic.tags.map{|t|t.name}.join(','),
                   data: { role: 'tagsinput' }, placeholder: 'space delimited'
  = f.primary 'Save changes'
  =< link_to 'Cancel', question_path(@topic), class: 'btn btn-default'

app/views/topics/home.html.slim
h1 Latest questions
hr
.row
  .col-md-9
    ul#questions = render @topics
  .col-md-3
p.lead
  ' Looking for more? Browse the
  = link_to 'complete list of questions', questions_path
  ' , or <i>popular tags</i>. Help us answer <i>unanswered questions</i>.

= subscribe_to '/topics/new'

app/views/topics/index.html.slim
- if params[:search]
  h1 Search results for '#{params[:search]}'
- else
  h1 Questions
hr
.row
  .col-md-9
    ul#questions = render @topics
  .col-md-3

app/views/topics/new.html.slim
= bootstrap_nested_form_for @topic, url: questions_path do |f|
  = f.text_field :title, autofocus: true
  = f.fields_for :question do |q|
    = q.text_area :body, hide_label: :true, rows: 10
    = f.text_field :tags, value: @topic.tags.map{|t|t.name}.join(','),
                   data: { role: 'tagsinput' }, placeholder: 'space delimited'
    = q.fields_for :attachments do |a|
      = a.file_field :file, hide_label: true
      = a.form_group
        = a.link_to_remove 'delete'
    = q.form_group
      = q.link_to_add "add file", :attachments
  =f.submit 'Post your question', class: 'btn btn-primary'

app/views/topics/show.html.slim
h1 = @topic.title
hr
.row
  .col-md-9
    .question = render @topic.question

    section#answers
      - if @topic.has_answers?
        = render 'answers', answers: @topic.answers,
          answers_count: @topic.answers_count

    hr
    - if user_signed_in?
      - if @topic.answered_by? current_user
        = render 'answered', topic: @topic
      - else
        = bootstrap_nested_form_for @answer, type: :js,
          url: question_answers_path(@topic), remote: true do |f|
          = f.text_area :body, label: 'Your answer', rows: 10
          = f.fields_for :attachments do |a|
            = a.file_field :file, hide_label: true
            = a.form_group
              = a.link_to_remove 'delete'
          = f.form_group
            = f.link_to_add "add file", :attachments
          = f.primary 'Post your answer', data: { disable_with: 'Submitting...' }
    - else
      p
        ' You should
        => link_to 'sign in', new_user_session_path
        ' or
        => link_to 'sign up', new_user_registration_path
        | to answer this question

  .col-md-3
    table.question-info
      tr
        td asked
        td.value = timeago_tag @topic.created_at
      tr
        td viewed
        td.value = pluralize @topic.views, 'time'
    h4 Related

#topic-id.hidden data-id="#{@topic.id}"
= subscribe_to "/topics/#{@topic.id}/comments"

app/views/topics/subscribe.js.erb
var link = $('.subscription');
link.text('unsubscribe');
link.attr('href', '<%= unsubscribe_question_path(resource) %>');

app/views/topics/unsubscribe.js.erb
var link = $('.subscription');
link.text('subscribe');
link.attr('href', '<%= subscribe_question_path(resource) %>');