config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :questions, controller: 'topics', except: [:destroy] do
    resources :answers, controller: 'messages',
              only: [:create, :edit, :update] do
      post :accept, on: :member
      post :voteup, on: :member
      post :votedown, on: :member
    end
    post :subscribe, on: :member
    post :unsubscribe, on: :member
  end

  resources :messages, only: [] do
    resources :comments, only: [:create]
  end

  resources :users, only: [:show, :edit, :update]

  resources :tags, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, controller: 'topics',
                only: [:index, :show, :create] do
        resources :answers, controller: 'messages',
                  only: [:index, :show, :create]
      end
    end
  end

  root 'topics#home'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :omniauthable,
         omniauth_providers: [:github, :facebook]

  has_many :authorizations, dependent: :destroy
  has_many :messages, foreign_key: 'author_id', inverse_of: :author
  has_many :comments, foreign_key: 'author_id', inverse_of: :author
  has_many :received_reputation_changes, class_name: 'ReputationChange',
           foreign_key: 'receiver_id', inverse_of: :receiver
  has_many :committed_reputation_changes, class_name: 'ReputationChange',
           foreign_key: 'committer_id', inverse_of: :committer
  has_many :votes
  has_many :subscriptions

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  attr_accessor :provider, :uid

  def self.subscribed_to(topic)
    joins(:subscriptions).where(subscriptions: { topic_id: topic })
  end

  def self.find_for_oauth(auth)
    auth_small = auth.slice(:provider, :uid)
    authorization = Authorization.where(auth_small).first
    return authorization.user if authorization

    user = User.where(email: auth.info[:email]).first
    if user
      user.authorizations.create! auth_small
    else
      user = User.new_for_oauth(auth)
    end
    user
  end

  def self.new_for_oauth(auth)
    User.new do |u|
      u.provider = auth.provider
      u.uid = auth.uid
      u.name = auth.info.name
      u.email = auth.info.email
      u.password = Devise.friendly_token[0, 20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      data = session['devise.omniauth_data'] &&
             session['devise.omniauth_data']['extra']['raw_info']
      if data
        user.name = data['name'] unless user.name?
        user.email = data['email'] unless user.email?
      end
    end
  end

  after_create :save_authorization, if: :provider

  private

  def save_authorization
    authorizations.create! provider: provider, uid: uid
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  respond_to :json

  def index
    respond_with({ users: collection })
  end

  def me
    respond_with({ user: current_resource_owner })
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook; auth; end
  def github; auth; end

  private

  def auth
    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      provider = request.env['omniauth.auth'].provider.titleize
      set_flash_message(:notice, :success, kind: provider) if is_navigational_format?
    else
      session['devise.omniauth_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  before_action :authenticate_user!, except: [:show]
  actions :show, :edit, :update

  load_and_authorize_resource

  def show
    @questions = Topic.with_questions_by resource
    @answers = Topic.with_answers_by resource
    @reputation_changes = ReputationChange.received_by resource
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/views/users/edit.html.slim
.h1 #{@user.name} &ndash; edit
hr
= bootstrap_form_for @user do |f|
  = f.text_field :name, autofocus: true
  => f.primary 'Save profile'
  = link_to 'Cancel', @user, class: 'btn btn-default'
hr
= link_to 'edit your registration info', edit_user_registration_path
span.text-muted<
  | (password and email)

app/views/users/show.html.slim
h1 = @user.name
hr
.row.user-profile
  .col-md-2.avatar
    = gravatar_image_tag @user.email, alt: @user.name,
       gravatar: { size: 150 }
    .reputation = @user.reputation
    p reputation
  .col-md-6.data
    - if @user == current_user
      p = link_to 'edit profile', edit_user_path(current_user)
    table
      tbody
        tr
          th rowspan='2' visits
          td member since
          td = @user.created_at.strftime '%B %d, %Y'
        tr
          td seen
          td = timeago_tag @user.last_sign_in_at
      tbody
        tr
          th stats
          td profile views
          td NA


h3 Summary
hr
.row.user-summary
  .col-md-6
    h4 Answers
    ul
      - @answers.each do |answer|
        li = link_to answer['title'], answer_path(answer)
    h4 Questions
    ul
      - @questions.each do |topic|
        li = link_to topic.title, question_path(topic)
  .col-md-6
    h4 Reputation
    table.reputation
      - @reputation_changes.each do |change|
        - change = ReputationChangeDecorator.new change
        tr
          td: span class="#{change.amount_class}" = change.amount_value
          td: span.time = timeago_tag change.time
          td: span = change.type_string
          td: span = link_to change.title, question_path(change.id)