config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :questions, controller: 'topics', except: [:destroy] do
    resources :answers, controller: 'messages',
              only: [:create, :edit, :update] do
      post :accept, on: :member
      post :voteup, on: :member
      post :votedown, on: :member
    end
    post :subscribe, on: :member
    post :unsubscribe, on: :member
  end

  resources :messages, only: [] do
    resources :comments, only: [:create]
  end

  resources :users, only: [:show, :edit, :update]

  resources :tags, only: [:index]

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, controller: 'topics',
                only: [:index, :show, :create] do
        resources :answers, controller: 'messages',
                  only: [:index, :show, :create]
      end
    end
  end

  root 'topics#home'
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title StackOverflow (clone)
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body

    nav.navbar.navbar-default role="navigation"
      .container
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target="#navbar-collapse-1"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#{root_path}"
            ' StackOverflow
            small clone
        .collapse.navbar-collapse#navbar-collapse-1
          ul.nav.navbar-nav
            = nav_link_to 'Ask question', new_question_path, {}, wrapper: 'li'
            = nav_link_to 'Tags', tags_path, {}, wrapper: 'li'
          form.navbar-form.navbar-left action="/questions" method="get" role="search"
            .form-group>
              = text_field_tag :search, params[:search],
                               class: 'form-control', placeholder: 'Search'
            button type="submit" class="btn btn-default" name=""
              span.glyphicon.glyphicon-search
          p.navbar-text.navbar-right
            - if user_signed_in?
              ' Signed in as
              => link_to current_user.name, user_path(current_user), class: 'navbar-link'
              | (
              = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'navbar-link'
              | )
            - else
              => link_to 'Sign in', new_user_session_path, class: 'navbar-link'
              ' |
              = link_to 'Sign up', new_user_registration_path, class: 'navbar-link'

    main
      .container

        - flash.each do |type, msg|
          div class="alert #{bootstrap_flash(type)} fade in"
            button.close type="button" data-dismiss="alert" aria-hidden="true" &times;
            = msg

        == yield

    footer.text-muted
      .container
        .text-center Judge a man by his questions rather than by his answers. ~ Voltaire